version: '3.2'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - 8080:80
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''